### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [insanehong/ama#1]
Screenshot please. I ask everyone this as it can tell a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by insanehong** [comment]
It's my screenshot of my iPhone home 

![img_0459](https://cloud.githubusercontent.com/assets/1558742/8738483/d8722e18-2c6a-11e5-8912-c39a1972446c.PNG)
