### ISSUE TITLE
스피커 초대권에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by wormslab** [insanehong/ama#13]
안녕하세요.
스피커를 통해 초대를 받았는데 메일에 별다른 메일수신이 없어서 제대로 초대가 된건지 궁금합니다.

스피커는 이병준@SKP 이구요. 
수신자는 wormslab@gmail.com, jangwhan@gmail.com 두명입니다.

확인 부탁드려요~

**Comment by insanehong** [comment]
https://github.com/playnodeconf/ama/issues/6 요기 답변을 달아드렸습니다.
